from typing import List, Dict, Any
from datetime import datetime


class ReportGenerator:
    # Generates reports from R.A.I.D. workflow results.
    
    def generate_report(self, data: List[Dict[str, Any]], 
                       findings: List[Dict[str, Any]], 
                       correlations: List[Dict[str, Any]]) -> Dict[str, Any]:
        # Generate a comprehensive report.
        findings_with_evidence = self._attach_evidence_to_findings(data, findings)

        summary = {
            'records_processed': len(data),
            'findings_count': len(findings),
            'severity_distribution': self._calculate_severity_distribution(findings)
        }
        if correlations:
            summary['correlations_count'] = len(correlations)

        report = {
            'summary': summary,
            'findings': findings_with_evidence,
        }

        if correlations:
            report['correlations'] = correlations
        
        return report
    
    def generate_text_report(self, data: List[Dict[str, Any]], 
                            findings: List[Dict[str, Any]], 
                            correlations: List[Dict[str, Any]]) -> str:
        # Generate a human-readable text report.
        findings_with_evidence = self._attach_evidence_to_findings(data, findings)
        
        lines = []
        lines.append("=" * 80)
        lines.append("R.A.I.D. THREAT HUNTING REPORT")
        lines.append("=" * 80)
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        
        # Disclaimer
        lines.append("DISCLAIMER:")
        lines.append("-" * 80)
        lines.append("This report is generated by R.A.I.D., a detection and analysis tool.")
        lines.append("Findings may NOT be 100% accurate and could contain false positives/negatives.")
        lines.append("All findings MUST be independently verified through manual analysis.")
        lines.append("Use this report as a starting point for investigation, not as definitive proof.")
        lines.append("")
        
        # Summary
        lines.append("SUMMARY")
        lines.append("-" * 80)
        summary = {
            'records_processed': len(data),
            'findings_count': len(findings),
            'severity_distribution': self._calculate_severity_distribution(findings)
        }
        lines.append(f"Records Processed: {summary['records_processed']}")
        lines.append(f"Findings Detected: {summary['findings_count']}")
        lines.append(f"Correlations: {len(correlations)}")
        lines.append("")
        
        # Severity Distribution
        lines.append("Severity Distribution:")
        severity_dist = summary['severity_distribution']
        lines.append(f"  - Critical: {severity_dist.get('critical', 0)}")
        lines.append(f"  - High: {severity_dist.get('high', 0)}")
        lines.append(f"  - Medium: {severity_dist.get('medium', 0)}")
        lines.append(f"  - Low: {severity_dist.get('low', 0)}")
        lines.append("")
        
        # Findings
        if findings_with_evidence:
            lines.append("FINDINGS")
            lines.append("=" * 80)
            for i, finding in enumerate(findings_with_evidence, 1):
                lines.append(f"\nFinding {i} - {finding.get('id', 'N/A')}")
                lines.append("-" * 80)
                lines.append(f"Detector: {finding.get('detector', 'N/A')}")
                lines.append(f"Severity: {finding.get('severity', 'N/A').upper()}")
                lines.append(f"Type: {finding.get('event_type', 'N/A')}")
                lines.append(f"Description: {finding.get('description', 'N/A')}")
                
                # Extract source files from matched records.
                matched_records = self._match_records_for_finding(data, finding)
                source_files = sorted(set(record.get('log_file', 'Unknown') for record in matched_records if record.get('log_file')))
                if source_files:
                    if len(source_files) == 1:
                        lines.append(f"Source File: {source_files[0]}")
                    else:
                        lines.append(f"Source Files:")
                        for source_file in source_files:
                            lines.append(f"  - {source_file}")
                
                lines.append("")
                
                # Details
                details = finding.get('details', {})
                if details:
                    lines.append("Details:")
                    for key, value in details.items():
                        if isinstance(value, list):
                            lines.append(f"  {key}:")
                            for item in value:
                                if isinstance(item, dict):
                                    lines.append(f"    - {item}")
                                else:
                                    lines.append(f"    - {item}")
                        elif isinstance(value, dict):
                            lines.append(f"  {key}:")
                            for k, v in value.items():
                                lines.append(f"    {k}: {v}")
                        else:
                            lines.append(f"  {key}: {value}")
                    lines.append("")
                
                # MITRE ATT&CK
                tactics = finding.get('mitre_tactics', [])
                techniques = finding.get('mitre_techniques', [])
                if tactics or techniques:
                    lines.append("MITRE ATT&CK:")
                    if tactics:
                        lines.append(f"  Tactics: {', '.join(tactics)}")
                    if techniques:
                        lines.append(f"  Techniques:")
                        for tech in techniques:
                            lines.append(f"    - {tech}")
                    lines.append("")
                
                # Matched Events
                matched_records = self._match_records_for_finding(data, finding)
                matched_count = finding.get('matched_events_count', len(matched_records))
                lines.append(f"Matched Events: {matched_count}")
                
                if matched_records:
                    lines.append("Event Details:")
                    # Show up to 10 matched events
                    for j, record in enumerate(matched_records[:10], 1):
                        lines.append(f"  Event {j}:")
                        lines.append(f"    Timestamp: {record.get('timestamp', 'N/A')}")
                        lines.append(f"    Event Type: {record.get('event_type', 'N/A')}")
                        
                        # Windows Event specific fields
                        if record.get('event_id'):
                            lines.append(f"    Event ID: {record.get('event_id')}")
                        if record.get('computer'):
                            lines.append(f"    Computer: {record.get('computer')}")
                        if record.get('source'):
                            lines.append(f"    Source: {record.get('source')}")
                        
                        # Security event fields
                        if record.get('source_ip'):
                            lines.append(f"    Source IP: {record.get('source_ip')}")
                        if record.get('username'):
                            lines.append(f"    Username: {record.get('username')}")
                        if record.get('user'):
                            lines.append(f"    User: {record.get('user')}")
                        
                        # PowerShell specific fields
                        if record.get('script_block'):
                            script_preview = record.get('script_block', '')[:150].replace('\n', ' ')
                            lines.append(f"    Script Preview: {script_preview}...")
                        
                        # Process creation fields
                        if record.get('new_process_name'):
                            lines.append(f"    Process: {record.get('new_process_name')}")
                        if record.get('command_line'):
                            cmd_preview = record.get('command_line', '')[:100]
                            lines.append(f"    Command: {cmd_preview}")
                        
                        # Generic fields
                        if record.get('message'):
                            lines.append(f"    Message: {record.get('message')[:100]}")
                    
                    if len(matched_records) > 10:
                        lines.append(f"  ... and {len(matched_records) - 10} more events")
        else:
            lines.append("")
            lines.append("NO FINDINGS DETECTED")
        
        # Correlations
        if correlations:
            lines.append("\n" + "=" * 80)
            lines.append("CORRELATIONS")
            lines.append("=" * 80)
            for i, corr in enumerate(correlations, 1):
                lines.append(f"\nCorrelation {i}")
                lines.append("-" * 80)
                lines.append(f"Finding IDs: {', '.join(corr.get('finding_ids', []))}")
                lines.append(f"Reason: {corr.get('reason', 'N/A')}")
                lines.append("")
        
        # Footer
        lines.append("")
        lines.append("=" * 80)
        lines.append("END OF REPORT")
        lines.append("=" * 80)
        
        return "\n".join(lines)
    
    def _calculate_severity_distribution(self, findings: List[Dict[str, Any]]) -> Dict[str, int]:
        # Calculate the distribution of findings by severity.
        distribution = {'low': 0, 'medium': 0, 'high': 0, 'critical': 0}
        
        for finding in findings:
            severity = finding.get('severity', 'low').lower()
            if severity in distribution:
                distribution[severity] += 1
        
        return distribution
    
    def _attach_evidence_to_findings(self, data: List[Dict[str, Any]], findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        enriched_findings: List[Dict[str, Any]] = []

        for finding in findings:
            matched_records = self._match_records_for_finding(data, finding)
            total_matched_events = len(matched_records)
            enriched_finding = dict(finding)
            enriched_finding = self._strip_sample_details(enriched_finding)
            enriched_finding['matched_events_count'] = total_matched_events
            enriched_findings.append(enriched_finding)

        return enriched_findings

    def _match_records_for_finding(self, data: List[Dict[str, Any]], finding: Dict[str, Any]) -> List[Dict[str, Any]]:
        event_type = finding.get('event_type')
        source_ip = finding.get('source_ip')
        username = finding.get('username')

        if event_type in ['potential_brute_force', 'suspicious_user_activity', 'account_spraying', 'suspicious_failed_logons']:
            candidates = [
                record for record in data
                if record.get('event_type') in ['failed_login', 'invalid_user']
            ]
            if source_ip:
                candidates = [record for record in candidates if record.get('source_ip') == source_ip]
            if username:
                candidates = [record for record in candidates if record.get('username') == username]
            return candidates

        if event_type == 'high_process_creation_rate':
            candidates = [record for record in data if record.get('event_type') == 'process_creation']
            if username:
                candidates = [record for record in candidates if record.get('username') == username]
            return candidates

        if event_type == 'suspicious_powershell':
            return [record for record in data if record.get('event_type') == 'script_execution']

        if event_type == 'excessive_firewall_blocks':
            candidates = [record for record in data if record.get('event_type') == 'firewall_block']
            if source_ip:
                candidates = [record for record in candidates if record.get('source_ip') == source_ip]
            return candidates

        fallback = []
        for record in data:
            if source_ip and record.get('source_ip') != source_ip:
                continue
            if username and record.get('username') != username:
                continue
            if event_type and record.get('event_type') == event_type:
                fallback.append(record)

        return fallback

    def _strip_sample_details(self, finding: Dict[str, Any]) -> Dict[str, Any]:
        details = finding.get('details')
        if not isinstance(details, dict):
            return finding

        cleaned_details = dict(details)
        noisy_sample_keys = ['scripts', 'failed_logins', 'attempts', 'blocks', 'processes']
        for key in noisy_sample_keys:
            cleaned_details.pop(key, None)

        finding['details'] = cleaned_details
        return finding